//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawOfficeDesktopApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public decimal MinimumOrBasePrice { get; set; }
        public Nullable<decimal> MaximumPrice { get; set; }
    }
}
